### ISSUE TITLE
summarise() masks dplyr::summarise()

### ISSUE THREAD

**Issue by sfirke** [hofnerb/papeR#43]
I am trying out papeR for managing data labels.  I didn't know it had a `summarise` function and was unhappy that it masks `dplyr::summarise`.  Thankfully this only tripped me up for a few minutes but I could see it giving a newer user a pretty big headache.

With papeR loaded after dplyr:
```
> mtcars %>%
+   group_by(cyl) %>%
+   summarise(mpg = mean(mpg))
Error in is.data.frame(x) : 
  (list) object cannot be coerced to type 'double'
In addition: Warning message:
In mean.default(data, na.rm = TRUE) :
  argument is not numeric or logical: returning NA
```
Is the conflict with dplyr::summarise intentional?  Would you consider a different function name to avoid this conflict?  I'll load `papeR` first going forward but that won't help others.

**Comment by DevMui** [comment]
Agreed. `tidyverse` is quite widely used by many R users. Changing the function name would reduce possible confusion.

**Comment by hofnerb** [comment]
I agree that this might be an issue. 

However, there aren't many function names which are natural to summarize data. Hence, both packages do use the same function name (please note that both spellings `summarize` and `summarise` exist in both packages). As it would break all code relying on `papeR::summarize`/`papeR::summarise` I do not intend to change the name. 

Unfortunately, I also do not see an (easy) way to define a generic that calls either papeR's or dplyr's version of the function as both work on data.frames (amongst others)? I cannot check right now as my R version is outdated and I cannot easily update R. If you see an oportunity to define a generic in papeR which calls either the papeR or the dplyr function depending on the requested functionality I would be happy to implement that.

Having said all this, I want to remind you that while loading the package(s) you should be warned about the masking of functions and hence I do not see a real issue here. That happens often and is in the remit of the user to check for this.

**Comment by sfirke** [comment]
Does `papeR::summarise` make sense - or even work - on a grouped data.frame?  Because `dplyr::summarise` is almost always used on a grouped data.frame, in my experience.

Perhaps a call of `papeR::summarise` on a data.frame could check to see if the data.frame is grouped, using `dplyr::is_grouped_df`.  If it is grouped, and if the call to `summarise` fails, then it could return a warning asking if the user meant to user dplyr::summarise instead.

That wouldn't require renaming or reworking your code base, and I think would avoid 90%+ of the user frustration.

**Comment by hofnerb** [comment]
I guess your suggestion or a similar solution using an S3 generic would do the trick: I'll try to look into this in the next days.

**Comment by hofnerb** [comment]
@sfirke: Regardig the question if `papeR::summarize` makes sense on grouped DFs, the very simple answer is yes of course. A grouped DF is upon my reasearch only an enriched `data.frame` with additional class attributes and further attributes on the groupes. 

The only problem is the different behavior of `data[, i]` with i beeing scalar. While this results in a vector for normal data frames, it remains a data frame for tibbles.

**Comment by hofnerb** [comment]
Should work (better) now.

First of all, when loading the packages, R tells the user that functions are masked:
```R
library("dplyr")
# The following objects are masked from ‘package:stats’:
#     filter, lag
# The following objects are masked from ‘package:base’:
#     intersect, setdiff, setequal, union
library("papeR")
# The following object is masked from ‘package:dplyr’: ## by car
#     recode
# The following objects are masked from ‘package:dplyr’: ## by papeR
#     summarise, summarize
# The following object is masked from ‘package:utils’:
#     toLatex
```
Additionally, I've now added a warning when `papeR::summarize` is called on `tbl` objects and fixed the bug(s) in `papeR::summarize` which resulted in the error reported by @sfirke (added `drop =TRUE ` in some places when data sets are subsetted). 
```R
mtcars$vs <- as.factor(mtcars$vs)
mtcars$am <- as.factor(mtcars$am)
summarize(mtcars, type = "numeric")
# Factors are dropped from the summary
#         N     Mean     SD     Min     Q1 Median     Q3    Max
# 1  mpg 32    20.09   6.03   10.40  15.35  19.20  22.80  33.90
# 2  cyl 32     6.19   1.79    4.00   4.00   6.00   8.00   8.00
# 3 disp 32   230.72 123.94   71.10 120.65 196.30 334.00 472.00
# 4   hp 32   146.69  68.56   52.00  96.00 123.00 180.00 335.00
# 5 drat 32     3.60   0.53    2.76   3.08   3.70   3.92   4.93
# 6   wt 32     3.22   0.98    1.51   2.54   3.33   3.65   5.42
# 7 qsec 32    17.85   1.79   14.50  16.88  17.71  18.90  22.90
# 8 gear 32     3.69   0.74    3.00   3.00   4.00   4.00   5.00
# 9 carb 32     2.81   1.62    1.00   2.00   2.00   4.00   8.00
summarize(mtcars, type = "factor")
# Non-factors are dropped from the summary
#      Level    N    %
# 1 vs     0   18 56.2
# 2        1   14 43.8
# 3 am     0   19 59.4
# 4        1   13 40.6
```
 Now the same with a grouped table
```R
by_cyl <- mtcars %>% group_by(cyl)
summarize(by_cyl, type = "numeric")

## (same results as above but additional the following warning)

# Warning message:
# In summarize(by_cyl, type = "numeric") :
#   This is a call to papeR::summarize. If you want to use the dplyr function explizitly call dplyr::summarize() # on your data.
summarize(by_cyl, type = "factor")

## (same results as above but additional the following warning)

# Warning message:
# In summarize(by_cyl, type = "factor") :
#   This is a call to papeR::summarize. If you want to use the dplyr function explizitly call dplyr::summarize() # on your data.
```
The very same happens if one calls the function on an ungrouped tibble such as `mtcars_tbl <- as_tbl(mtcars)`.

**Comment by sfirke** [comment]
I appreciate you addressing this @hofnerb - thanks!
